spring:
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        query.substitutions: true 1, false 0
        default_batch_fetch_size: 50
        jdbc.batch_size: 50
        order_inserts: true
        max_fetch_depth: 2
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        connection.zeroDateTimeBehavior: convertToNull

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: trustserver:9092
#192.168.239.129:9092,192.168.239.129:9093,192.168.239.129:9094
          zkNodes: trustserver:2181
#192.168.239.129:2181

# Discovery Server Access
eureka:
  instance:
    hostname: trustserver
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://trustserver:1111/eureka/

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
  threadpool.default.coreSize: 10

customconf:
  user:
    serverurl: http://www.otato.com.cn:23101
    auth:
      # apiurl: http://124.205.224.180:9074
      apiurl: http://x.walker.asia:7071
      granttype: client_credentials
      clientid: admin
      clientsecret: password
      commonverifyface:
        threshold: 0.8
    datafile:
      root: /root/appserver
    ex:
      busevitaskdetailurl: http://www.otato.com.cn:2000/business/evidence?task=detail&id=
      carloantaskdetailurl: http://www.otato.com.cn:2000/business/car?task=detail&id=
    linkface:
      apiurl: https://v1-auth-api.visioncloudapi.com
      apiid: 2cbe8866040f498693593b1de4fdce37
      apisecret: ee601f68fed24e82b6c0bff7092a26c7
      confidence: 0.8
    baidu:
      apikey: api_key
      secretkey: secret_key
      vopapi:
        cuid: www.otato.com.cn
        threshold: 0.7
  product:
    liveness:
      baseUrl: http://192.168.1.80
      codebaseUrl: http://192.168.1.80/static/livedetector.cab#version=1,0,0,1
  pay:
    wxpay:
      notifyUrl: http://x.walker.asia:23141/user/orderNotify
      appid: wxf96e6c9b7f13c96a
      mch_id: 1485159242
      total_fee: 1
      spbill_create_ip: 192.168.1.1
      trade_type: NATIVE
      trade_key: 148515924214851592422017topcancn
      device_info: WEB

webRemotConf:
  order:
    websocketUrl: ws://www.otato.com.cn:23101/websocket
    remoteDesUrl: https://cz.xhgzc.cn/bh/jar
    guacamoleUrl: http://www.otato.com.cn:8080/guacamole
    rdphost: b64>>eC53YWxrZXIuYXNpYQ==
    rdpport: 8443
    rdphostname: x.walker.asia
    rdphostpwd: 12345678
    rdphostport: 3389
    guacconnid: 2
    winPath: D:\\gongzheng
    linPath: /root/appserver/order_service
web:
  notary_short_name: 永欣公证master-github
  notary_full_name: 宁波永欣公证处master-github
  notary_phone: 0574-87723751
  logo_img: images/logo_ygz.png
my-config:

  appName: my-app-chentianhui


