spring:
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        query.substitutions: true 1, false 0
        default_batch_fetch_size: 50
        jdbc.batch_size: 50
        order_inserts: true
        max_fetch_depth: 2
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        connection.zeroDateTimeBehavior: convertToNull

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: trustserver:9092
#192.168.239.129:9092,192.168.239.129:9093,192.168.239.129:9094
          zkNodes: trustserver:2181
#192.168.239.129:2181

# Discovery Server Access
eureka:
  instance:
    hostname: trustserver
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://trustserver:1111/eureka/

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
  threadpool.default.coreSize: 10

customconf:
  pay:
    wxpay:
      notifyUrl: http://cz.xhgzc.cn:23141/user/orderNotify
      appid: wxf96e6c9b7f13c96a
      mch_id: 1485159242
      total_fee: 3000
      spbill_create_ip: 192.168.1.1 
      trade_type: NATIVE
      trade_key: 148515924214851592422017topcancn
      device_info: WEB

  user:
    serverurl: http://183.134.75.40:23101
    auth:
      apiurl: http://122.228.11.110:7071
      granttype: client_credentials
      clientid: hangzxhNotarialOffice
      clientsecret: e43085c4f06fd664429a8ac4d1f6ad66
      commonverifyface:
        threshold: 0.7
    datafile:
      root: /root/appserver
    ex:
      busevitaskdetailurl: http://183.134.75.40:2000/business/evidence?task=detail&id=
      busevitaskdetailurl4ent: http://183.134.75.40:2000/business/entevi?type=bq&task=detail&&id=
      carloantaskdetailurl: http://183.134.75.40:2000/business/car?task=detail&id=
      managerurl: http://183.134.75.40:2000
    linkface:
      apiurl: https://v1-auth-api.visioncloudapi.com
      apiid: 2cbe8866040f498693593b1de4fdce37
      apisecret: ee601f68fed24e82b6c0bff7092a26c7
      confidence: 0.6
    baidu:
      apikey: iuMIFw50E1owt679FmPaA6wb
      secretkey: 69182fd1207435c5d72a467e5bd95e60
      vopapi:
        cuid: cz.xhgzc.cn
        threshold: 0.7
  product:
    liveness:
      baseUrl: http://183.134.75.40:7080
      codebaseUrl: http://183.134.75.40:7080/static/livedetector.cab#version=1,0,0,1
webRemotConf:
  order:
    websocketUrl: ws://183.134.75.40:23101/websocket
    remoteDesUrl: https://183.134.75.40/bh/jar
    guacamoleUrl: http://183.134.75.40:2280/guacamole
    rdphost: b64>>eC53YWxrZXIuYXNpYQ==
    rdpport: 8443
    rdphostname: 192.168.1.157
    rdphostpwd: Cloud@13691511450
    rdphostport: 3389
    guacconnid: 1
    winPath: D:\\gongzheng
    linPath: /root/appserver/order_service
web:
  notary_short_name: 西湖公证github
  notary_full_name: 杭州市西湖公证处github
  notary_phone: 0571-88393341-github
  logo_img: images/logo.png

